### PR TITLE
chore: honk with sound

### PR DESCRIPTION
**Pull request by troubadour-hell**
### Background

beep 3 times when dae honk.

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full Changelogs

- [Implement ...]

### Issue Reference

Closes #_[issue number]_

### CODE REVIEW

**Comment by mzz2017** [comment]
Could you please paste the screenshot of the result? Thank you!

**Comment by troubadour-hell** [comment]
> Could you please paste the screenshot of the result? Thank you!

image

**Comment by troubadour-hell** [comment]
> Could you please paste the screenshot of the result? Thank you!

image

**Review by yqlbu — APPROVED** [review]

**Comment by nicholas-opensource** [comment]
> > Could you please paste the screenshot of the result? Thank you!
> 
> image

Such a you thing to do

**Pull request merged**
