### PR TITLE
feat/refactor: support the node-level proxy chain

### PR DESCRIPTION
**Pull request by mzz2017**
### Background

This PR implements node-level proxy chain.

See https://github.com/daeuniverse/dae/discussions/236

Scheme:
```bash
node {
  new_node_name: 'node link 1 (endpoint) -> node link 2 (relay)'
}
```

Example:
```bash
node {
  # case 1: tuic over vless (different nodes)
  chains: 'tuic://my.endpoint.com:18364/xxxxx -> vless://ohmy.relay.com:12212/xxxxx'

  # case 2: socks5 over wss (same server port, so wss is the transport layer)
  chains2: 'socks5://yeeeah.v2raya.org:6999 -> wss://yeeeah.v2raya.org:6999/7cadf625-171c-4002-7abc-257f6485fcc2'
}
```

Moreover, if you are a subscription maker, you can also use such expressions in your subscription content. And then encode them with base64:
```
tuic://my_tuic_link -> vmess://my_vmess_link
ss://my_ss_link -> vmess://my_vmess_link
```

### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [x] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full changelogs

- [Implement ...]

### Test Result

image

### Future Work

We need to support the group-level proxy chains:
```
group1 -> group2
```

### CODE REVIEW

**Comment by mzz2017** [comment]
Test Result (socks5 + wss):
image

**Comment by yqlbu** [comment]
Link to https://github.com/daeuniverse/dae/discussions/236

**Review by yqlbu — APPROVED** [review]
Working as expected, thanks for the efforts 💪

**Review by yqlbu — APPROVED** [review]

**Comment by mzz2017** [comment]
Test Result (from CTO):
image

**Pull request merged**
