### PR TITLE
feat: support tuic v5

### PR DESCRIPTION
**Pull request by mzz2017**
### Background

Support [TUIC v5](https://github.com/EAimTY/tuic/blob/tuic-5.0.0/SPEC.md).

NOTICE: `tuic v5` may have traffic cutoff problems. But this problem varies from person to person, mainly depending on local network quality.

### Proposed link format

Full parameters:
```
tuic://uuid:password@example.com:port?congestion_control=cubic&alpn=h3,spdy/3.1&sni=example.com&allow_insecure=0&disable_sni=0&udp_relay_mode=native
```

Mini parameters:
```
tuic://uuid:password@example.com:port?alpn=h3&udp_relay_mode=native&congestion_control=cubic
```

> **Warning**: `alpn` must be the same as what is present in the server configuration. Please refer to [tuic-server#configuration](https://github.com/EAimTY/tuic/tree/dev/tuic-server#configuration)

### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOG
- [x] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full changelogs

- Implement TUIC.
- Upgrade go mod [softwind](https://github.com/mzz2017/softwind/commit/4603642fac262a88ef3a3642beaed3399fa15aa1).

### Special thanks [Clash.Meta](https://github.com/MetaCubeX/Clash.Meta/)

### CODE REVIEW

**Comment by kunish** [comment]
What do you mean traffic cutoff problem?

**Comment by mzz2017** [comment]
> What do you mean traffic cutoff problem?

Multiple consecutive speed tests may result in subsequent traffic suspension or connections timeout.

**Comment by pomhg** [comment]
Screenshot 2023-07-07 at 01 42 41
The latest binary from action doesn't work. The 'beta' bin from the group works. I only changed the tuic node part in the config.

**Comment by mzz2017** [comment]
The `devided by zero` problem has been fixed.

**Comment by mzz2017** [comment]
测试结果：

image
image
image

**Comment by yqlbu** [comment]
@mzz2017 Let's wait for test results in `daed`. Do we need to update `dae-wing`?

**Comment by yqlbu** [comment]
Please also update `Proposed link format` in correspondent `/docs` and `example.dae`

**Comment by mzz2017** [comment]
@yqlbu Do we need to create a precedent for tuic?

**Comment by yqlbu** [comment]
I've tested the overall functionality - working like a charm 🛸

**Comment by yqlbu** [comment]
Let's add `tuic` in [this line](https://github.com/daeuniverse/dae/blob/main/example.dae#L110).

**Comment by yqlbu** [comment]
I've created a dedicated discussion page where we can put notes together - #182

**Review by yqlbu — DISMISSED** [review]
Thanks for bringing in such an amazing feature! Appreciated the efforts 💪🏻

**Comment by mzz2017** [comment]
UDP has severe performance problems. I'm fixing it. Do not merge.

**Comment by mzz2017** [comment]
Ready to test and merge.

**Comment by yqlbu** [comment]
@mzz2017 Let me do a final round of testing, hopefully, can get this merged by the end of today. I will get back to you with the testing result regarding stability.

**Review by yqlbu — APPROVED** [review]
🚀

**Pull request merged**
