### PR TITLE
feat: support ipip tunnel as lan/wan interface

### LINKED ISSUE #614: [Bug Report] Unable to use an IPIP tunnel as a LAN interface
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

When using an IPIP tunnel as a LAN interface, the LAN network becomes unreachable. After investigation, I discovered that the failure to retrieve the link header length caused the eBPF processing to terminate prematurely without properly redirecting the traffic.

### Expected Behavior

_No response_

### Steps to Reproduce

1. Setup IPIP tunnel.
2. Configure the tunnel as a LAN interface.
3. Attempt to request or access a service within the LAN network.
4. Observe that the LAN network is unreachable.

### Environment

- **Dae version (use `dae --version`)**: 0.8.0rc1
- **OS (e.g `cat /etc/os-release`)**: Archlinux
- **Kernel (e.g. `uname -a`)**: 6.10.6-arch1-1
- **Others**:

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pcmid**
### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full Changelogs

- [Implement ...]

### Issue Reference

Closes #614

### CODE REVIEW

**Comment by mzz2017** [comment]
你有测试环境吗，请确认是否正常工作？

**Comment by pcmid** [comment]
@mzz2017 在我的环境中测试是没有问题的

**Review by jschwinger233 — APPROVED** [review]
Thanks! 

In future maybe we can get linkHdrLen based on the the L2 addr, e.g. if `ip --br link` shows zero mac addr with NOARP, then it's an L2-less device. (We just need to translate `ip --br link` command into API callings.)

**Comment by pcmid** [comment]
> Thanks!
> 
> In future maybe we can get linkHdrLen based on the the L2 addr, e.g. if `ip --br link` shows zero mac addr with NOARP, then it's an L2-less device. (We just need to translate `ip --br link` command into API callings.)

We can check the size of `LinkAttrs.HardwareAddr`, a size of 0 might indicate that it's an L2-less device.

**Comment by pcmid** [comment]
Are there any other issues that need to be resolved with this PR?

**Review by mzz2017 — APPROVED** [review]

**Pull request merged**
