### PR TITLE
optimize(udp)/fix(quicSniffer): optimize performance of udp and fix a potential panic of quic

### LINKED ISSUE #343: [Bug Report] 代理 HTTP/3 异常
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

无法代理 HTTP/3 流量

### Expected Behavior

正常代理 HTTP/3 流量

### Steps to Reproduce

主路由运行 daed，配置如下

```
pname(NetworkManager, systemd-resolved, dnsmasq) -> must_direct
dip(geoip:private) -> direct
dip(geoip:cn) -> direct
fallback: proxy
```

proxy 协议为 ss aead

测试机网线直连主路由

在国外服务器上搭建 UDP echo server，脚本如下
```python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# Author: David Manouchehri <manouchehri@protonmail.com>
# This script will always echo back data on the UDP port of your choice.
# Useful if you want nmap to report a UDP port as "open" instead of "open|filtered" on a standard scan.
# Works with both Python 2 & 3.

import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

server_address = '0.0.0.0'
server_port = 31337

server = (server_address, server_port)
sock.bind(server)
print("Listening on " + server_address + ":" + str(server_port))

while True:
        payload, client_address = sock.recvfrom(1)
        print("Echoing data back to " + str(client_address))
        sent = sock.sendto(payload, client_address)
```

```
➜  ~ python3 echo.py
Listening on 0.0.0.0:31337
```

在本机运行 echo clinet

脚本如下

```python
#!/usr/bin/env python 
# Python Network Programming Cookbook, Second Edition -- Chapter - 1 
# This program is optimized for Python 2.7.12 and Python 3.5.2. 
# It may run on any other version with/without modifications. 
 
import socket 
import sys 
import argparse 
 
data_payload = 2048
 
def echo_client(host, port, msg): 
    """ A simple echo client """ 
    # Create a UDP socket 
    sock = socket.socket(socket.AF_INET, 
                         socket.SOCK_DGRAM) 
 
    server_address = (host, port) 
    print ("Connecting to %s port %s" % server_address) 
 
    try: 
 
        # Send data 
        message = msg
        print ("Sending %s" % message) 
        sent = sock.sendto(message.encode
               ('utf-8'), server_address) 
 
        # Receive response 
        data, server = sock.recvfrom(data_payload) 
        print ("received %s" % data) 
 
    finally: 
        print ("Closing connection to the server") 
        sock.close() 
 
if __name__ == '__main__': 
    parser = argparse.ArgumentParser(description='Socket Server Example') 
    parser.add_argument('--port', action="store", dest="port", type=int, required=True) 
    parser.add_argument('--host', action="store", dest="host", type=str, required=True)
    parser.add_argument('--msg', action="store", dest="msg", type=str, required=True)
    given_args = parser.parse_args()  
    port = given_args.port 
    echo_client(given_args.host,port, given_args.msg) 

```

命令如下，正常得到结果

```
❯ python3 a.py --host echo_server_ip --port 31337 --msg 3
Connecting to echo_server_ip port 31337
Sending 3
received b'3'
Closing connection to the server
```

daed 日志显示正常转发了流量

```
time="Oct 16 14:21:02" level=info msg="192.168.33.101:52733 <-> echo_server_ip:31337" dialer=dler-sg-to-sg domain= dscp=0 ip="echo_server_ip:31337" mac="e0:d5:5e:8c:2f:db" network=udp4 outbound=proxy pid=0 pname= policy=min_moving_avg
```

服务端日志

```
➜  ~ python3 echo.py
Listening on 0.0.0.0:31337
Echoing data back to ('proxy server ip', 52277)
data b'3'
```

至此证明 UDP 流量可以正常被代理

但是用 HTTP/3 工具测试时，无法通过 HTTP/3 访问网站

```
❯ docker run -it --rm ymuski/curl-http3 curl -IL --http3 -4 -v https://cloudflare-quic.com/
* processing: https://cloudflare-quic.com/
*   Trying 172.67.9.235:443...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*   Trying 172.67.9.235:443...
* Connected to cloudflare-quic.com (172.67.9.235) port 443
* ALPN: offers h2,http/1.1
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Apr 10 00:00:00 2023 GMT
*  expire date: Apr  9 23:59:59 2024 GMT
*  subjectAltName: host "cloudflare-quic.com" matched cert's "cloudflare-quic.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: HEAD]
* h2 [:scheme: https]
* h2 [:authority: cloudflare-quic.com]
* h2 [:path: /]
* h2 [user-agent: curl/8.2.1-DEV]
* h2 [accept: */*]
* Using Stream ID: 1
> HEAD / HTTP/2
> Host: cloudflare-quic.com
> User-Agent: curl/8.2.1-DEV
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
HTTP/2 200 
< date: Mon, 16 Oct 2023 14:24:46 GMT
date: Mon, 16 Oct 2023 14:24:46 GMT
< content-type: text/html
content-type: text/html
< content-length: 125959
content-length: 125959
< server: cloudflare
server: cloudflare
< cf-ray: 8170f7a45fe14b7a-SIN
cf-ray: 8170f7a45fe14b7a-SIN
< alt-svc: h3=":443"; ma=86400
alt-svc: h3=":443"; ma=86400

< 
* Connection #0 to host cloudflare-quic.com left intact
```

daed 日志

```
time="Oct 16 14:24:46" level=info msg="192.168.33.101:55662 <-> cloudflare-quic.com:443" dialer=dler-sg-to-sg domain=cloudflare-quic.com dscp=0 ip="172.67.9.235:443" mac="e0:d5:5e:8c:2f:db" network=udp4 outbound=proxy pid=0 pname= policy=min_moving_avg
```

在代理服务器上测试

```
root@sg1:~# docker run -it --rm ymuski/curl-http3 curl -IL --http3 -4 -v https://cloudflare-quic.com/
* processing: https://cloudflare-quic.com/
*   Trying 104.22.8.38:443...
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*  subjectAltName: host "cloudflare-quic.com" matched cert's "cloudflare-quic.com"
* Connected to cloudflare-quic.com (104.22.8.38) port 443
* using HTTP/3
* Using HTTP/3 Stream ID: 0
> HEAD / HTTP/3
> Host: cloudflare-quic.com
> User-Agent: curl/8.2.1-DEV
> Accept: */*
> 
< HTTP/3 200 
HTTP/3 200 
< date: Mon, 16 Oct 2023 14:31:46 GMT
date: Mon, 16 Oct 2023 14:31:46 GMT
< content-type: text/html
content-type: text/html
< content-length: 125959
content-length: 125959
< server: cloudflare
server: cloudflare
< cf-ray: 817101e50fab4cdd-SIN
cf-ray: 817101e50fab4cdd-SIN
< alt-svc: h3=":443"; ma=86400
alt-svc: h3=":443"; ma=86400

< 
* Connection #0 to host cloudflare-quic.com left intact
```

### Environment

- **Dae version (use `dae --version`)**: daed version 0.4.0rc1
- **OS (e.g `cat /etc/os-release`)**: ImmortalWrt 23.05.0-rc3 r26804-a3639e76d6
- **Kernel (e.g. `uname -a`)**: Linux ImmortalWrt 5.15.120 #0 SMP Mon Jul 24 10:07:07 2023 x86_64 GNU/Linux
- **Others**:

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mzz2017**
#### Fix panic

When a quic first packet is insufficient, the re-assembler will panic due to being out of range. This PR fixes it.

#### Support cross-packet reassembling for QUIC (SNI Sniff)

After this quic cross-packet reassembling, we can get SNI in more cases. However, quic connecting to google servers seems to be refused if the destination is overridden. Therefore, we can only use the quic sniffed domain for routing instead of dest overriding.

#### UDP Performance

And this PR improves UDP performance.

Before:

image

After:

image

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full Changelogs

- Check range before copy.
- Upgrade quic-go to v0.38.1.
- GSO prototype on dae side (NOT READY).
- Use AnyFromPool to reduce syscall consumption.

### Issue Reference

Closes #343

### CODE REVIEW

**Review by yqlbu — DISMISSED** [review]

**Comment by mzz2017** [comment]
Hold it. We need to improve the stream sniffer instead of just skip the problem.

I'll convert it into a draft.

**Comment by mzz2017** [comment]
Ready for review.

**Review by yqlbu — APPROVED** [review]

**Comment by yqlbu** [comment]
Tested again earlier in the day. No more panic issues occurred.

**Comment by yqlbu** [comment]
> Tested again earlier in the day. No more panic issues occurred.

I observed some abnormal issue earlier in the day. DNS is not working quite well. Also, the embed video on YouTube was not able to load and play automatically. We need further investigation on this.

**Comment by mzz2017** [comment]
> > Tested again earlier in the day. No more panic issues occurred.
> 
> I observed some abnormal issues earlier in the day. DNS is not working quite well. Also, the embed video on YouTube was not able to load and play automatically. We need further investigation on this.

Sniffing should work fine now. Please test it again, thanks.

**Comment by yqlbu** [comment]
TCP is working as expected. However, there is a noticeable speed discrepancy in UDP connection. Let’s gather more feedbacks from the end-users.

**Comment by mzz2017** [comment]
https://t.me/daeuniverse/119500

It is recommended to merge in advance.
And the bug should be fixed later.

**Comment by mzz2017** [comment]
cc @yqlbu

**Review by yqlbu — APPROVED** [review]

**Comment by yqlbu** [comment]
Link to #355.

**Pull request merged**
