### PR TITLE
fix: incidental packet drop and weird UDP state maintaining

### LINKED ISSUE #513: [Bug Report] UDP connection state cannot be maintained
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation

### Current Behavior

Since #505, there is a noticeable bug that correlates to UDP state management. Connection is no longer maintained as expected, which further results in receiving invalid response.

image

### Expected Behavior

NA

### Steps to Reproduce

```dae
# config.dae

include {
    config.d/*.dae
}

global {
    tproxy_port: 12345
    so_mark_from_dae: 0
    log_level: trace

    tcp_check_url: 'http://cp.cloudflare.com,1.1.1.1,2606:4700:4700::1111'
    tcp_check_http_method: CONNECT
    udp_check_dns: 'dns.google.com:53,8.8.8.8,2001:4860:4860::8888'
    check_interval: 60s

    check_tolerance: 100ms

    wan_interface: ens18
    lan_interface: ens19

    dial_mode: domain++
    allow_insecure: false
    auto_config_kernel_parameter: true

    sniffing_timeout: 10000ms

    tls_implementation: tls
    utls_imitate: chrome_auto
}
```

### Environment

- **Dae version (use `dae --version`)**: dae-v0.6.0rc2
- **OS (e.g `cat /etc/os-release`)**: NixOS 24.05 (Uakari)
- **Kernel (e.g. `uname -a`)**: Linux nixos-sdwan-gateway 6.8.6-cachyos #1-NixOS SMP PREEMPT_DYNAMIC Sat Apr 13 11:10:12 UTC 2024 x86_64 GNU/Linux
- **Others**: I use Nix BTW

### Anything else?

I've tested the exact same configuration with version `v0.6.0rc1`, and did not experience such an issue. As a result, the issue might be originated from #505.

### PR DESCRIPTION
**Pull request by mzz2017**
#### ebpf drop

The past two PRs #493, #505 have introduced a weird problem: erroneous UDP status maintenance will occur when a large number of concurrent messages are sent.

This results in some packets of stateful udp connection being incorrectly sent directly (such as what should be proxied and sent to dae control plane), resulting in sporadic packet drop. May be relevant: https://github.com/daeuniverse/dae/pull/533#issuecomment-2163408055.

This problem is particularly likely to be triggered when the original traffic is udp and the throughput is large, such as http3 traffic and bt traffic.

Although I haven't fully verified, this fix may incidentally resolve the DNS leak issue.

#### unordered udp packets

The data which should be in order will be handled as unordered by dae, which may cause more resources by quic to process.

### Checklist

- [ ] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full Changelogs

- [Implement ...]

### Issue Reference

Closes #513

### Test Result

NA

### CODE REVIEW

**Comment by mnixry** [comment]
Thank you! The fix has been confirmed to work effectively in my local tests. HTTP/3 connections are now able to maintain a reasonable speed.



In real-world scenarios, HTTP/3 now enables smooth playback of 4K videos at 60fps on YouTube without buffering, a feat that was nearly impossible before.

**Comment by mnixry** [comment]
Further testing has shown that HTTP/3 upload speeds still drop to zero after a short time. The following command can be used to establish a benchmark for this issue:

```
./curl -X POST --form file=@/tmp/test.bin -Lv --http3-only "https://h3.speed.cloudflare.com/__up" > /dev/null
```

image

The results from <https://h3.speed.cloudflare.com/> also indicate there is a problem:

image

**Comment by jschwinger233** [comment]
Maybe also fix https://github.com/daeuniverse/dae/issues/513? Orz

**Comment by mzz2017** [comment]
> Further testing has shown that HTTP/3 upload speeds still drop to zero after a short time. 

Thanks for your rapid feedback. I have reproduced this problem.

**Comment by mzz2017** [comment]
I observed an interesting phenomenon. Like yours, the data was disconnected after sending 1023K.

**Comment by mzz2017** [comment]
@mnixry It seems that the data should be in-order and dae handle all packets as unordered. I'll fix it soon.

**Comment by mzz2017** [comment]
@mnixry I've pushed a commit https://github.com/daeuniverse/dae/pull/539/commits/ba6239408a347cd277edc0b4c14fbd68a0a2531a that may fix the problem. Could you please take a try?

**Pull request merged**
