### PR TITLE
ci/feat(build,pr-build,seed-build): integrate check runs to report build status

### PR DESCRIPTION
**Pull request by yqlbu**
### Background

Integrate check runs to report build status. Replicate https://github.com/daeuniverse/daed/pull/162

Relevant workflows:

- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/instantiate-check-runs/action.yml
- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/report-check-run/action.yml
- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/report-workflow-run/action.yml

References:

- [Github API - Check Runs](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28)
- [About GitHub status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks)
- [Github checks API vs check runs vs check suites](https://stackoverflow.com/questions/67919168/github-checks-api-vs-check-runs-vs-check-suites)

### Checklist

- [x] The Pull Request has been fully tested
- [ ] There's an entry in the CHANGELOGS
- [ ] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full changelogs

- ci(pr-build): integrate check runs to report build status
- ci(pr-build): integrate individual check run per stage
- ci(seed-build): add build-type input
- patch(seed-build): use string type for build-type
- refactor(daily-build): rework workflow logic
- refactor(build): rework main-build logic

### Issue reference

NA

### Test Result

https://github.com/daeuniverse/dae/actions/runs/5556529422

image

image

## New PR Build Structure

image

### CODE REVIEW

**Comment by yqlbu** [comment]
There are some issues with `secret management` as prerequisites for `GitHub Check-Run`; working on a fix now, hence, this PR should be marked as in a `stale` state.

**Comment by yqlbu** [comment]
> There are some issues with `secret management` as prerequisites for `GitHub Check-Run`; working on a fix now, hence, this PR should be marked as in a `stale` state.

The issue has been fixed in https://github.com/daeuniverse/daed/pull/167

**Review by mzz2017 — APPROVED** [review]

**Comment by mzz2017** [comment]
LGTM

**Comment by yqlbu** [comment]
> LGTM

Let me test one more scenario before we merge it.

**Comment by yqlbu** [comment]
> > LGTM
> 
> Let me test one more scenario before we merge it.

Issues related to `pre-actions` seed workflow has been resolved - https://github.com/daeuniverse/dae-1/actions/runs/5565874796

Source: https://github.com/daeuniverse/ci-seed-jobs/blob/master/.github/workflows/pre-actions.yml#L92-L107

**Pull request merged**
