### PR TITLE
docs: create zh global and dns docs

### PR DESCRIPTION
**Pull request by troubadour-hell**
### Background

Translated the most difficult part to understand.

### Checklist

- [x] The Pull Request has been fully tested
- [x] There's an entry in the CHANGELOGS
- [x] There is a user-facing docs PR against https://github.com/daeuniverse/dae

### Full changelogs

- docs: add zh global and dns docs

### Issue reference

NA

### Test Result

NA

### CODE REVIEW

**Comment by mzz2017** [comment]
Good job!

Feel free to tell me if you are ready to review.

**Comment by troubadour-hell** [comment]
> Good job!
> 
> Feel free to tell me once it is ready to review.

It's ready.

**Review by yqlbu — COMMENTED** [review]
Looks great in general. However, we do NOT have `docs/zh/configuration/global.md` ATM. Would you like to create one, please?

**Comment by troubadour-hell** [comment]
> Looks great in general. However, we do NOT have ATM. Would you like to create one, please?`docs/en/configuration/global.md`

It is translated from part of `example.dae`. I have no idea if it is necessary to create such a file.

**Review by mzz2017 — CHANGES_REQUESTED** [review]

**Comment by yqlbu** [comment]
If we add `global.md` to `/docs/`, we will need to maintain two copies of `config.example`, which drastically increases maintenance overheads. Hence, I propose to get rid of `global.md`. cc @mzz2017 @troubadour-hell

**Comment by yqlbu** [comment]
> If we add `global.md` to `/docs/`, we will need to maintain two copies of `config.example`, which drastically increases maintenance overheads. Hence, I propose to get rid of `global.md`. cc @mzz2017 @troubadour-hell

@mzz2017 Any thoughts on this?

**Comment by mzz2017** [comment]
@yqlbu We can put it in a discussion (as community-maintained version) and refer it in example.dae.

**Review by yqlbu — APPROVED** [review]

**Pull request merged**
